services:

    # services
    shapecode_twig_template_event.services.event:
        class: Shapecode\Bundle\TwigTemplateEventBundle\Services\EventService
        arguments: ["@service_container"]

    # handler
    shapecode_twig_template_event.event_handler.include:
        class: Shapecode\Bundle\TwigTemplateEventBundle\Event\Handler\IncludeHandler

    shapecode_twig_template_event.event_handler.render:
        class: Shapecode\Bundle\TwigTemplateEventBundle\Event\Handler\RenderHandler
        arguments: ["@fragment.handler"]

    shapecode_twig_template_event.event_handler.string:
        class: Shapecode\Bundle\TwigTemplateEventBundle\Event\Handler\StringHandler

    # twig extensions
    shapecode_twig_template_event.twig_extension.event:
        class: Shapecode\Bundle\TwigTemplateEventBundle\Twig\EventExtension
        arguments: ["@shapecode_twig_template_event.services.event"]
        tags:
            - { name: twig.extension }
